### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by hellodineshgarg** [edoko/react-js-sample#1]
C:\Users\nisha\Documents\GitHub\react-js-sample>npm install
npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/e
nv to update!

> uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\nisha\Documents\GitHub\react-js-sample\node_modules\uglifyjs-webpack-plugin
> node lib/post_install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-js-sample@1.0.6 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"
win32","arch":"x64"})

added 1400 packages in 476.658s

C:\Users\nisha\Documents\GitHub\react-js-sample>npm start

> react-js-sample@1.0.6 start C:\Users\nisha\Documents\GitHub\react-js-sample
> NODE_ENV=production ./node_modules/.bin/babel-node server

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-js-sample@1.0.6 start: `NODE_ENV=production ./node_modules/.bin/babel-node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-js-sample@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nisha\AppData\Roaming\npm-cache\_logs\2018-04-21T21_59_54_388Z-debug.log

C:\Users\nisha\Documents\GitHub\react-js-sample>

**Comment by edoko** [comment]
Can you install win-node-env ?

> npm install -g win-node-env

And, re-try npm start please

**Comment by hellodineshgarg** [comment]
now getting below error

C:\Users\nisha\Documents\GitHub\react-js-sample>npm start

> react-js-sample@1.0.6 start C:\Users\nisha\Documents\GitHub\react-js-sample
> webpack -d --watch

No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! react-js-sample@1.0.6 start: `webpack -d --watch`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the react-js-sample@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nisha\AppData\Roaming\npm-cache\_logs\2018-05-02T01_13_46_440Z-debug.log

**Comment by hellodineshgarg** [comment]
Now it is working thank you
