### ISSUE TITLE
Cant not run project

### ISSUE THREAD

**Issue by havantuan** [edoko/react-js-sample#2]
npm start

> react-js-sample@1.0.6 start E:\REACT_LABO\react-js-sample
> NODE_ENV=production ./node_modules/.bin/babel-node server

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-js-sample@1.0.6 start: `NODE_ENV=production ./node_modules/.bin/babel-node server`
......
Help me

**Comment by edoko** [comment]
update new package.json

you try windows os : npm run start-win
you try mac, linux os : npm run start-other

try it :)
